--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Kingom1/PocketMine-MP
build-by-default: true
branches:
- stable
projects:
  tests.plugins.TesterPlugin:
    path: tests/plugins/TesterPlugin/
...
